config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
  	resources :comments
  end
  root "posts#index"

  get '/about', to: 'pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
    belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments, dependent: :destroy
    belongs_to :user
    validates :title, presence: true, length: {minimum: 5}
	validates :body,  presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments, dependent: :destroy
  has_many :posts, dependent: :destroy
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.new(params[:comment].permit(:body))
		@comment.user = current_user
		@comment.save

		redirect_to post_path(@post)

	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy

		redirect_to post_path(@post)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
		@posts = Post.all.order('created_at DESC')
	end

  def new
    @post = Post.new
	end

	def show
	  @post = Post.find(params[:id])
	end

  def create
    @post = Post.new(post_params)
    @post.user = current_user


    if @post.save
      flash[:success] = "Post was successfully created"
			redirect_to @post
		else
			render 'new'
    end
    

  end
  
  def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])

		if @post.update(params[:post].permit(:title, :body))
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy

		redirect_to posts_path
	end

	private

	def post_params
		params.require(:post).permit(:title, :body)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
  <div class="comment_content">
    <p class="comment-user"><%= comment.user&.email %></p>
		<p class="comment_body"><%= comment.body %></p>
		<p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago</p>
	</div>
  <% if user_signed_in? && comment.user == current_user %>
	<p><%= link_to 'Delete', [comment.post, comment],
								  method: :delete,
								  class: "button",
								 	data: { confirm: 'Are you sure?' } %></p>
  <% end %>
</div> 

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
	<%= f.label :body %><br>
	<%= f.text_area :body %><br>
	<br>
	<%= f.submit %>
<% end %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div id="sidebar">
		<div id="logo">
		</div>

		<ul>
			<li><%= link_to "Blog", root_path %></li>
			<li><%= link_to "About", about_path %></li>
		</ul>

		<% if !user_signed_in? %>
			<p class="sign_in"><%= link_to "Login", new_user_session_path %></p>
		<% end %>
	</div>

	<div id="main_content">
		<div id="header">
			<% if current_page?(root_path) %>
				<p>All Posts</p>
			<% elsif current_page?(about_path) %>
				<p>About</p>
			<% else %>
				<%= link_to "Back to All Posts", root_path %>
			<% end %>

			<% if user_signed_in? %>
				<div class="buttons">
					<button class="button"><%= link_to "New Post", new_post_path %></button>
          <button class="button">
            <%= link_to('Logout', destroy_user_session_path, method: :delete) %>     
          </button>
				</div>
			<% end %>
		</div>

		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert") %>
		<% end %>

		<%= yield %>
	</div>
  </body>
</html>

app/views/pages/about.html.erb
this site has built later

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
		<div id="errors">
			<h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving:</h2>
			<ul>
				<% @post.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<%= f.label :title %><br>
	<%= f.text_field :title %><br>
	<br>
	<%= f.label :body %><br>
	<%= f.text_field :body %><br>
	<br>
	<%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
	<h1>Edit Post</h1>

	<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
	<div class="post_wrapper">
		<h2 class="title"><%= link_to post.title, post %></h2>
		<p class="date"><%= post.created_at.strftime("%B %d, %Y") %></p>
	</div>
<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
	<h1>New Post</h1>

	<%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
  <h1 class="title"><%= @post.title %></h1>
  <p class="date">
		Submitted <%= time_ago_in_words(@post.created_at) %> Ago
		<% if user_signed_in? && @post.user == current_user %>
		| <%= link_to 'Edit', edit_post_path(@post) %> |
		  <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>
		<% end %>
  </p>
  <p class="body"><%= @post.body %></p>
  <% if user_signed_in? %>
  <div id="comments">
		<h2><%= @post.comments.count %> Comments</h2>
		<%= render @post.comments %>

		<h3>Add a comment:</h3>
		<%= render "comments/form" %>
	</div>
	<% end %>
</div> 